function [log_f] = log_f_VG(x, lambda, alpha, beta, mu)
%LOG_F_VG Summary of this function goes here
%   Detailed explanation goes here

log_f = lambda * log(alpha^2 - beta^2) ...
    - (1/2 * log(pi) + log(gamma(lambda)) + (lambda - 1/2) * log(2 * alpha)) ...
    + (lambda - 1/2) * log(abs(x - mu)) ...
    + log(besselk(lambda - 1/2, alpha * abs(x - mu))) ...
    + beta * (x - mu);

end
